language: python
python:
  - "2.7"
install:
  - pip install --upgrade cython>=0.28.1
  - pip install --upgrade .
  - python setup.py build_ext --inplace
  - pip install pylint
  - pip install python-coveralls
script:
  - ./run_presubmit.sh
after_success:
  # Upload coverage data to coveralls.io.
  - coveralls
